name: vintage_vision
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0 

  cupertino_icons: ^1.0.8

  video_player: ^2.9.3
  flick_video_player: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/assets/video/2073224.mp4
    - lib/assets/video/7864918.mp4
    - lib/assets/video/13203001.mp4

  
  fonts:
    - family: Limelight
      fonts:
        - asset: lib/assets/fonts/Limelight-Regular.ttf

    - family: LilyScriptOne
      fonts:
        - asset: lib/assets/fonts/LilyScriptOne-Regular.ttf